//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 12:38:52 PM CEST 
//


package dk.os2opgavefordeler.model.kle_import;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HovedgruppeKomponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HovedgruppeKomponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HovedgruppeNr"/>
 *         &lt;element name="HovedgruppeTitel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HovedgruppeVejledning" type="{}VejledningKomponent"/>
 *         &lt;element name="HovedgruppeAdministrativInfo" type="{}KLEAdministrativInfoKomponent"/>
 *         &lt;element name="HovedgruppeFilter" type="{}FilterKomponent" minOccurs="0"/>
 *         &lt;element name="Gruppe" type="{}GruppeKomponent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HovedgruppeKomponent", propOrder = {
    "hovedgruppeNr",
    "hovedgruppeTitel",
    "hovedgruppeVejledning",
    "hovedgruppeAdministrativInfo",
    "hovedgruppeFilter",
    "gruppe"
})
public class HovedgruppeKomponent {

    @XmlElement(name = "HovedgruppeNr", required = true)
    protected String hovedgruppeNr;
    @XmlElement(name = "HovedgruppeTitel", required = true)
    protected String hovedgruppeTitel;
    @XmlElement(name = "HovedgruppeVejledning", required = true)
    protected VejledningKomponent hovedgruppeVejledning;
    @XmlElement(name = "HovedgruppeAdministrativInfo", required = true)
    protected KLEAdministrativInfoKomponent hovedgruppeAdministrativInfo;
    @XmlElement(name = "HovedgruppeFilter")
    protected FilterKomponent hovedgruppeFilter;
    @XmlElement(name = "Gruppe", required = true)
    protected List<GruppeKomponent> gruppe;

    /**
     * Gets the value of the hovedgruppeNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedgruppeNr() {
        return hovedgruppeNr;
    }

    /**
     * Sets the value of the hovedgruppeNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedgruppeNr(String value) {
        this.hovedgruppeNr = value;
    }

    /**
     * Gets the value of the hovedgruppeTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedgruppeTitel() {
        return hovedgruppeTitel;
    }

    /**
     * Sets the value of the hovedgruppeTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedgruppeTitel(String value) {
        this.hovedgruppeTitel = value;
    }

    /**
     * Gets the value of the hovedgruppeVejledning property.
     * 
     * @return
     *     possible object is
     *     {@link VejledningKomponent }
     *     
     */
    public VejledningKomponent getHovedgruppeVejledning() {
        return hovedgruppeVejledning;
    }

    /**
     * Sets the value of the hovedgruppeVejledning property.
     * 
     * @param value
     *     allowed object is
     *     {@link VejledningKomponent }
     *     
     */
    public void setHovedgruppeVejledning(VejledningKomponent value) {
        this.hovedgruppeVejledning = value;
    }

    /**
     * Gets the value of the hovedgruppeAdministrativInfo property.
     * 
     * @return
     *     possible object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public KLEAdministrativInfoKomponent getHovedgruppeAdministrativInfo() {
        return hovedgruppeAdministrativInfo;
    }

    /**
     * Sets the value of the hovedgruppeAdministrativInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public void setHovedgruppeAdministrativInfo(KLEAdministrativInfoKomponent value) {
        this.hovedgruppeAdministrativInfo = value;
    }

    /**
     * Gets the value of the hovedgruppeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterKomponent }
     *     
     */
    public FilterKomponent getHovedgruppeFilter() {
        return hovedgruppeFilter;
    }

    /**
     * Sets the value of the hovedgruppeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterKomponent }
     *     
     */
    public void setHovedgruppeFilter(FilterKomponent value) {
        this.hovedgruppeFilter = value;
    }

    /**
     * Gets the value of the gruppe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gruppe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGruppe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GruppeKomponent }
     * 
     * 
     */
    public List<GruppeKomponent> getGruppe() {
        if (gruppe == null) {
            gruppe = new ArrayList<GruppeKomponent>();
        }
        return this.gruppe;
    }

}
