//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 12:38:52 PM CEST 
//


package dk.os2opgavefordeler.model.kle_import;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for EmneKomponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmneKomponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EmneNr"/>
 *         &lt;element name="EmneTitel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmneVejledning" type="{}VejledningKomponent" minOccurs="0"/>
 *         &lt;element name="EmneRetskildeReference" type="{}RetskildeReferenceKomponent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EmneAdministrativInfo" type="{}KLEAdministrativInfoKomponent"/>
 *         &lt;element ref="{}BevaringJaevnfoerArkivloven"/>
 *         &lt;element name="SletningJaevnfoerPersondataloven" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="EmneFilter" type="{}FilterKomponent" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmneKomponent", propOrder = {
    "emneNr",
    "emneTitel",
    "emneVejledning",
    "emneRetskildeReference",
    "emneAdministrativInfo",
    "bevaringJaevnfoerArkivloven",
    "sletningJaevnfoerPersondataloven",
    "emneFilter"
})
public class EmneKomponent {

    @XmlElement(name = "EmneNr", required = true)
    protected String emneNr;
    @XmlElement(name = "EmneTitel", required = true)
    protected String emneTitel;
    @XmlElement(name = "EmneVejledning")
    protected VejledningKomponent emneVejledning;
    @XmlElement(name = "EmneRetskildeReference")
    protected List<RetskildeReferenceKomponent> emneRetskildeReference;
    @XmlElement(name = "EmneAdministrativInfo", required = true)
    protected KLEAdministrativInfoKomponent emneAdministrativInfo;
    @XmlElement(name = "BevaringJaevnfoerArkivloven", required = true)
    protected String bevaringJaevnfoerArkivloven;
    @XmlElement(name = "SletningJaevnfoerPersondataloven")
    protected Duration sletningJaevnfoerPersondataloven;
    @XmlElement(name = "EmneFilter")
    protected FilterKomponent emneFilter;

    /**
     * Gets the value of the emneNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmneNr() {
        return emneNr;
    }

    /**
     * Sets the value of the emneNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmneNr(String value) {
        this.emneNr = value;
    }

    /**
     * Gets the value of the emneTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmneTitel() {
        return emneTitel;
    }

    /**
     * Sets the value of the emneTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmneTitel(String value) {
        this.emneTitel = value;
    }

    /**
     * Gets the value of the emneVejledning property.
     * 
     * @return
     *     possible object is
     *     {@link VejledningKomponent }
     *     
     */
    public VejledningKomponent getEmneVejledning() {
        return emneVejledning;
    }

    /**
     * Sets the value of the emneVejledning property.
     * 
     * @param value
     *     allowed object is
     *     {@link VejledningKomponent }
     *     
     */
    public void setEmneVejledning(VejledningKomponent value) {
        this.emneVejledning = value;
    }

    /**
     * Gets the value of the emneRetskildeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emneRetskildeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmneRetskildeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetskildeReferenceKomponent }
     * 
     * 
     */
    public List<RetskildeReferenceKomponent> getEmneRetskildeReference() {
        if (emneRetskildeReference == null) {
            emneRetskildeReference = new ArrayList<RetskildeReferenceKomponent>();
        }
        return this.emneRetskildeReference;
    }

    /**
     * Gets the value of the emneAdministrativInfo property.
     * 
     * @return
     *     possible object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public KLEAdministrativInfoKomponent getEmneAdministrativInfo() {
        return emneAdministrativInfo;
    }

    /**
     * Sets the value of the emneAdministrativInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public void setEmneAdministrativInfo(KLEAdministrativInfoKomponent value) {
        this.emneAdministrativInfo = value;
    }

    /**
     * Gets the value of the bevaringJaevnfoerArkivloven property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBevaringJaevnfoerArkivloven() {
        return bevaringJaevnfoerArkivloven;
    }

    /**
     * Sets the value of the bevaringJaevnfoerArkivloven property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBevaringJaevnfoerArkivloven(String value) {
        this.bevaringJaevnfoerArkivloven = value;
    }

    /**
     * Gets the value of the sletningJaevnfoerPersondataloven property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getSletningJaevnfoerPersondataloven() {
        return sletningJaevnfoerPersondataloven;
    }

    /**
     * Sets the value of the sletningJaevnfoerPersondataloven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setSletningJaevnfoerPersondataloven(Duration value) {
        this.sletningJaevnfoerPersondataloven = value;
    }

    /**
     * Gets the value of the emneFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterKomponent }
     *     
     */
    public FilterKomponent getEmneFilter() {
        return emneFilter;
    }

    /**
     * Sets the value of the emneFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterKomponent }
     *     
     */
    public void setEmneFilter(FilterKomponent value) {
        this.emneFilter = value;
    }

}
