//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 12:38:52 PM CEST 
//


package dk.os2opgavefordeler.model.kle_import;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GruppeKomponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GruppeKomponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GruppeNr"/>
 *         &lt;element name="GruppeTitel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GruppeVejledning" type="{}VejledningKomponent" minOccurs="0"/>
 *         &lt;element name="GruppeRetskildeReference" type="{}RetskildeReferenceKomponent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GruppeAdministrativInfo" type="{}KLEAdministrativInfoKomponent"/>
 *         &lt;element name="GruppeFilter" type="{}FilterKomponent" minOccurs="0"/>
 *         &lt;element name="Emne" type="{}EmneKomponent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GruppeKomponent", propOrder = {
    "gruppeNr",
    "gruppeTitel",
    "gruppeVejledning",
    "gruppeRetskildeReference",
    "gruppeAdministrativInfo",
    "gruppeFilter",
    "emne"
})
public class GruppeKomponent {

    @XmlElement(name = "GruppeNr", required = true)
    protected String gruppeNr;
    @XmlElement(name = "GruppeTitel", required = true)
    protected String gruppeTitel;
    @XmlElement(name = "GruppeVejledning")
    protected VejledningKomponent gruppeVejledning;
    @XmlElement(name = "GruppeRetskildeReference")
    protected List<RetskildeReferenceKomponent> gruppeRetskildeReference;
    @XmlElement(name = "GruppeAdministrativInfo", required = true)
    protected KLEAdministrativInfoKomponent gruppeAdministrativInfo;
    @XmlElement(name = "GruppeFilter")
    protected FilterKomponent gruppeFilter;
    @XmlElement(name = "Emne", required = true)
    protected List<EmneKomponent> emne;

    /**
     * Gets the value of the gruppeNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGruppeNr() {
        return gruppeNr;
    }

    /**
     * Sets the value of the gruppeNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGruppeNr(String value) {
        this.gruppeNr = value;
    }

    /**
     * Gets the value of the gruppeTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGruppeTitel() {
        return gruppeTitel;
    }

    /**
     * Sets the value of the gruppeTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGruppeTitel(String value) {
        this.gruppeTitel = value;
    }

    /**
     * Gets the value of the gruppeVejledning property.
     * 
     * @return
     *     possible object is
     *     {@link VejledningKomponent }
     *     
     */
    public VejledningKomponent getGruppeVejledning() {
        return gruppeVejledning;
    }

    /**
     * Sets the value of the gruppeVejledning property.
     * 
     * @param value
     *     allowed object is
     *     {@link VejledningKomponent }
     *     
     */
    public void setGruppeVejledning(VejledningKomponent value) {
        this.gruppeVejledning = value;
    }

    /**
     * Gets the value of the gruppeRetskildeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gruppeRetskildeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGruppeRetskildeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetskildeReferenceKomponent }
     * 
     * 
     */
    public List<RetskildeReferenceKomponent> getGruppeRetskildeReference() {
        if (gruppeRetskildeReference == null) {
            gruppeRetskildeReference = new ArrayList<RetskildeReferenceKomponent>();
        }
        return this.gruppeRetskildeReference;
    }

    /**
     * Gets the value of the gruppeAdministrativInfo property.
     * 
     * @return
     *     possible object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public KLEAdministrativInfoKomponent getGruppeAdministrativInfo() {
        return gruppeAdministrativInfo;
    }

    /**
     * Sets the value of the gruppeAdministrativInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link KLEAdministrativInfoKomponent }
     *     
     */
    public void setGruppeAdministrativInfo(KLEAdministrativInfoKomponent value) {
        this.gruppeAdministrativInfo = value;
    }

    /**
     * Gets the value of the gruppeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterKomponent }
     *     
     */
    public FilterKomponent getGruppeFilter() {
        return gruppeFilter;
    }

    /**
     * Sets the value of the gruppeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterKomponent }
     *     
     */
    public void setGruppeFilter(FilterKomponent value) {
        this.gruppeFilter = value;
    }

    /**
     * Gets the value of the emne property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emne property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmne().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmneKomponent }
     * 
     * 
     */
    public List<EmneKomponent> getEmne() {
        if (emne == null) {
            emne = new ArrayList<EmneKomponent>();
        }
        return this.emne;
    }

}
