//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 12:38:52 PM CEST 
//


package dk.os2opgavefordeler.model.kle_import;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetskildeReferenceKomponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetskildeReferenceKomponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="RetskildeTitel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParagrafEllerKapitel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RetsinfoAccessionsNr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetskildeReferenceKomponent", propOrder = {
    "retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr"
})
public class RetskildeReferenceKomponent {

    @XmlElementRefs({
        @XmlElementRef(name = "RetsinfoAccessionsNr", type = JAXBElement.class),
        @XmlElementRef(name = "RetskildeTitel", type = JAXBElement.class),
        @XmlElementRef(name = "ParagrafEllerKapitel", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr;

    /**
     * Gets the value of the retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getRetskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr() {
        if (retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr == null) {
            retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr = new ArrayList<JAXBElement<String>>();
        }
        return this.retskildeTitelAndParagrafEllerKapitelAndRetsinfoAccessionsNr;
    }

}
